### PR TITLE
Fixes the long-standing shiny modules problem

### LINKED ISSUE #100: Sortable and shiny modules are currently incompatible
Hey @andrie & @schloerke,

I've spent a handful of hours trying to figure out what's going on here and it looks like the issue goes beyond just the update module, it appears that the handling of the shiny input ids in sortable is incompatible with shiny modules. 
I've added a contrived example in [5c9f4f7](https://github.com/rstudio/sortable/pull/95/commits/5c9f4f7ae03326936d5a08de1a227e6889c086a4) that can be run with the console open. Clicking either of the buttons does not trigger the input methods.

I'm trying to hunt down the differences in how the `input_id` is handled in this package compared to others, but I'm wondering if anyone has a better understanding of what all needs to change to standardize the handling of the `input_id` argument internally such that `sortable` works in a modularized shiny app?

_Originally posted by @yogat3ch in https://github.com/rstudio/sortable/issues/95#issuecomment-1572834461_

### PR DESCRIPTION
**Pull request by andrie**
Fixes #100

### CODE REVIEW

**Comment by yogat3ch** [comment]
Sounds like solving this took a deep dive into the way shiny modules work to find the incompatibility. Thank you @andrie & @schloerke for sticking with this one long enough to resolve it!

File: R/zzz.R [hunk 1]
```diff
@@ -2,6 +2,18 @@
...
+  # use the `cli` package to send a message on startup to use `enable_modules()`
+  msg <- c("")
+  packageStartupMessage(
+    # rlang::inform("This message will appear only once per session.", .frequency = "once", .frequency_id = "sortable"),
+    rlang::inform(
+      cli::cli_text("To use sortable with shiny modules, run {.run sortable::enable_modules()} to opt into the new standard."),
+    .frequency = "once",
+    .frequency_id = "sortable"
+    )
+  )
```
Comment (schloerke) [inline R/zzz.R]: I believe this constant messaging and inconsistent behavior is harder to understand than a big "BREAKING CHANGE, all your sortable DOM IDs have been updated. <previous_format> is now <new_format>. You only need to worry if you have custom css. Thank you for your patience as we have learned from our mistakes." in the NEWS.md

This would remove the startup message, remove the sortable_env, remove the vignette for inconsistent behavior. 

I'd rather lean towards "at version X, the behavior changed to something simple and expected".
